### ISSUE TITLE
Test with 11-jre-hotspot-bionic 

### ISSUE THREAD

**Issue by gotson** [OIDAM98/openjdk-docker-arm#1]
Hi,

Would you be able to test with the base image `11-jre-hotspot-bionic`?

It seems the change from bionic to focal could be the culprit, I'd like to confirm this intuition.

**Comment by OIDAM98** [comment]
Sure! Will try it out in the afternoon and update you.

**Comment by OIDAM98** [comment]
Hi! I was able to change the base image's version to `11-jre-hotspot-bionic`.

Looks like you're correct! The message `OpenJDK Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes` no longer appears.
